app:
  build: .
  ports:
    - "3030:3030"
mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=mukaevilia44
    - MYSQL_DATABASE=studiu
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
